# Generated by Django 5.0 on 2023-12-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
