# Generated by Django 4.2.3 on 2023-12-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_space_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_space',
            old_name='dates_reserved',
            new_name='booking_date',
        ),
    ]
