# Generated by Django 4.2.3 on 2023-12-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.CharField()),
                ('category', models.CharField()),
                ('icon_id', models.IntegerField()),
            ],
        ),
    ]
