# Generated by Django 4.2.3 on 2023-12-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='no VIN provided', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=254),
        ),
    ]
