# Generated by Django 4.2.3 on 2023-12-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_remove_vehicle_color_vehicle_vin_alter_vehicle_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='client_id',
            field=models.IntegerField(),
        ),
    ]
