# Generated by Django 4.2.3 on 2023-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0003_alter_vehicle_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(default='Sowwy, no IMG', max_length=254),
        ),
    ]
